### PR TITLE
Clone VC before modifying it

### PR DESCRIPTION
**Pull request by sbihel**
I'm not sure this is the right way of doing it, but as it is the credential has the invalid `"statusListIndex": true` in the following tests (e.g. the interop ones).

### CODE REVIEW

**Comment by davidlehn** [comment]
Perhaps use [structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/Window/structuredClone).

**Comment by PatStLouis** [comment]
@sbihel this looks correct, can you please resolve the conflicts of your branch?

**Comment by sbihel** [comment]
@PatStLouis done

**Review by aljones15 — APPROVED** [review]
Use of structuredClone looks good, but watch out for errors with that method in future versions of node (node 23 for instance has issues). Thanks for the code @sbihel approved.

**Review by BigBlueHat — APPROVED** [review]

**Pull request merged**
